# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdb_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
